# Generated by Django 4.0.6 on 2022-08-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_canceld',
            field=models.BooleanField(default=False),
        ),
    ]
