# Generated by Django 4.0.6 on 2022-08-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_is_canceld'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_canceld',
            new_name='is_cancelled',
        ),
    ]
