# Generated by Django 4.1 on 2022-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_is_canceld_order_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('P', 'Pay on delivery'), ('C', 'Online payment')], default='Pay on delivery', max_length=20),
        ),
    ]
