# Generated by Django 4.1 on 2022-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Pay on delivery', 'Pay on delivery'), ('Online payment', 'Online payment')], default='Pay on delivery', max_length=20),
        ),
    ]
