# Generated by Django 4.1 on 2022-08-11 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
