# Generated by Django 4.1 on 2022-08-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0009_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('payment_method', models.CharField(choices=[('ON', 'Pay on delivery'), ('OFF', 'Online payment')], default='ON', max_length=3)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(default='Not required for pay on delivary', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='store.order')),
            ],
        ),
    ]
