# Generated by Django 4.1 on 2022-08-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_order_alter_orderitem_product'),
        ('payment', '0003_paymentmodel_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentModel',
            new_name='Payment',
        ),
    ]
