# Generated by Django 4.1 on 2022-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_paymentmodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('OFF', 'Pay on delivery'), ('ON', 'Online payment')], default='OFF', max_length=3),
        ),
    ]
