# Generated by Django 4.1 on 2022-08-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('OFF', 'Pay on delivery'), ('ONl', 'Online payment')], default='OFF', max_length=3),
        ),
    ]
